sudo: required
dist: stretch
language: bash
addons:
  apt:
    packages:
      - libreadline-dev
notifications:
  irc: "ircs://chat.freenode.net:7070/#p534"
before_script:
  - pushd ./config
  - ./build_bc.sh --no-check-signature
  - popd
script:
  - time source ./test.sh
